### ISSUE TITLE
cairo dll missing from dependencies

### ISSUE THREAD

**Issue by ShnitzelKiller** [dedoardo/polyfit#3]
only the .lib is present in the repository, causing cmake to throw an error in windows (the CMakeLists.txt claims that both should be bundled).

**Comment by dedoardo** [comment]
The claim has now been validated in the commit [https://github.com/dedoardo/polyfit/commit/9a0359a2c1daa2592d1bb900d505e13fdf510cc3](https://github.com/dedoardo/polyfit/commit/9a0359a2c1daa2592d1bb900d505e13fdf510cc3).

This DLL is just for Windows x64, let's leave the cross-platform issue to #4
